### ISSUE TITLE
Rename the initnramfs config files, currently still g8os

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-initramfs#42]
https://github.com/zero-os/0-initramfs/blob/master/config/g8os/g8os.toml

Agree @FastGeert?

When done so, we also need to update the documentation about this:
https://github.com/zero-os/0-core/blob/master/docs/config/main.md#main

**Comment by maxux** [comment]
Seems legit to me. I would like btw change the organisation of files in `config` directory on the same time.
