### ISSUE TITLE
Include tcpdump

### ISSUE THREAD

**Issue by delandtj** [zero-os/0-initramfs#60]
even if it's only temporarily, but it's a handy tool to verify if all is well configured and that switches are behaving properly

**Comment by maxux** [comment]
@grimpy Do you think it's a good idea to include debugging tools in debug mode (now there is a debug/release mode in the build) or in case of needing them, scp them in runtime ?

**Comment by grimpy** [comment]
After some discussion with @maxux we have decided to add some debug tools on the zero-os which allow you to easily mount a standard ubuntu flist which can provide you with all the tools you need.
